// Badge drop events. Edit this list to add real events.
// Dates are ISO 8601 (UTC). emoji is used as placeholder badge art —
// swap for an `image` URL if you have official badge images.
const BADGE_EVENTS = [
  {
    name: "Subtember Celebration Badge",
    channel: "Twitch",
    description: "Watch any participating stream for 2 hours during Subtember to earn this badge.",
    emoji: "🎉",
    requirement: "Watch 2 hours",
    start: "2026-09-01T17:00:00Z",
    end: "2026-09-30T17:00:00Z",
  },
  {
    name: "Summer Games Watch Badge",
    channel: "TwitchRivals",
    description: "Tune into Twitch Rivals Summer Games coverage to unlock an exclusive viewer badge.",
    emoji: "🏆",
    requirement: "Watch 1 hour",
    start: "2026-06-10T16:00:00Z",
    end: "2026-06-20T23:00:00Z",
  },
  {
    name: "Anime Marathon Badge",
    channel: "Crunchyroll",
    description: "Earn this badge by watching the official anime marathon stream.",
    emoji: "⛩️",
    requirement: "Watch 90 minutes",
    start: "2026-06-14T15:00:00Z",
    end: "2026-06-16T03:00:00Z",
  },
  {
    name: "Charity Stream Supporter",
    channel: "GamesDoneQuick",
    description: "Support the summer charity marathon and pick up a limited supporter badge.",
    emoji: "💜",
    requirement: "Cheer 100 bits",
    start: "2026-07-05T18:00:00Z",
    end: "2026-07-12T06:00:00Z",
  },
  {
    name: "Launch Day Hype Badge",
    channel: "PlayStation",
    description: "Watch the game launch showcase live to grab the hype badge.",
    emoji: "🚀",
    requirement: "Watch 30 minutes",
    start: "2026-06-25T19:00:00Z",
    end: "2026-06-25T23:00:00Z",
  },
  {
    name: "Spring Fest Flower Badge",
    channel: "Twitch",
    description: "This badge was available during the Spring Fest event for all sub gifters.",
    emoji: "🌸",
    requirement: "Gift 1 sub",
    start: "2026-04-01T17:00:00Z",
    end: "2026-04-15T17:00:00Z",
  },
  {
    name: "Esports Finals Badge",
    channel: "RiotGames",
    description: "Watch the grand finals broadcast with a linked account to earn this drop badge.",
    emoji: "⚔️",
    requirement: "Watch 1 hour",
    start: "2026-05-15T14:00:00Z",
    end: "2026-05-17T22:00:00Z",
  },
  {
    name: "Creator Camp Graduate",
    channel: "Twitch",
    description: "Complete the Creator Camp watch-along series to receive the graduate badge.",
    emoji: "🎓",
    requirement: "Watch 3 hours",
    start: "2026-08-03T16:00:00Z",
    end: "2026-08-28T16:00:00Z",
  },
];
